#ifndef FMS_H_
#define FMS_H_

typedef enum{
	 FMS_RECEIVE_STATE_IDLE,
	 FMS_RECEIVE_STATE_PREAMBLE,
	 FMS_RECEIVE_STATE_LENGTH_H,
	 FMS_RECEIVE_STATE_LENGTH_L,
	 FMS_RECEIVE_STATE_CMD_H,
	 FMS_RECEIVE_STATE_CMD_L,
	 FMS_RECEIVE_STATE_DATA,
	 FMS_RECEIVE_STATE_CRC_H,
	 FMS_RECEIVE_STATE_CRC_L,
	 FMS_RECEIVE_STATE_TAIL
}fms_state_t;

void DataFrame_Handle(void);


#endif
